plugins:
  - rubocop-rspec

Layout/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 12

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 4

RSpec/ExampleLength:
  Max: 14
